### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by nikic** [nikic/php-ast#103]
PHP 7.3 adds support for three new language features:

 * https://wiki.php.net/rfc/trailing-comma-function-calls
 * https://wiki.php.net/rfc/list_reference_assignment
 * https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes

We need to review if these require any changes in php-ast. I think we might need to add some flags handling for the `list()` change, while the other two should work as-is.

**Comment by TysonAndre** [comment]
For trailing-comma-function, it'd be useful to know so that applications could efficiently warn about backwards incompatibility. I don't think the information is available from php-src from skimming the code, you'd have a better idea.

I haven't seen any backwards incompatibility changes in my applications.

List reference assignment works the way I'd expect it to, I think, but it's been a while. I haven't looked closely at nowdoc/heredoc yet.

**Comment by nikic** [comment]
Indeed, looks like everything was already working fine. I've added an `ARRAY_ELEM_REF` flag in https://github.com/nikic/php-ast/commit/c62f10ffd7f341a8e83d865de6d7924cd105375c to avoid using `1` as a magic number, but the AST generation itself did not need adjustments.

> For trailing-comma-function, it'd be useful to know so that applications could efficiently warn about backwards incompatibility. I don't think the information is available from php-src from skimming the code, you'd have a better idea.

Yeah, we don't have that information in the AST.
