### ISSUE TITLE
Allow "@var" type comments on variables

### ISSUE THREAD

**Issue by aik099** [nikic/php-ast#32]
The code like this allows to ignore return type set in DocBlock of `makeClass` method and use one in `@var` comment instead.

```php
/** @var kEmail $email */
$email = $this->makeClass('....');
```

This is common approach when dealing with factory methods, that return class based on specific text (not necessary class name) given as input to the factory method.

This is currently a show stopper for https://github.com/etsy/phan/issues/313 .

**Comment by nikic** [comment]
As said in the referenced issue, we can't expose these comments because PHP does not collect them. I also doubt that it will do so in the future, as this information just isn't useful to PHP.

The issue also mentions that getting offset information may be useful -- this is currently tracked at https://bugs.php.net/bug.php?id=70024.
