### ISSUE TITLE
Will this module return t_comments? 

### ISSUE THREAD

**Issue by dericofilho** [nikic/php-ast#4]
In nikic/php-parser, for instance, it strips comments while generating the tree. Now that PHP 7 will likely be implemented using ASTs, I wonder whether comments will be kept.

**Comment by nikic** [comment]
Nope, this is still an abstract tree. You'll get doc comments for declarations, but everything else is discarded.

It would be nice to at least retain comments to the same degree as nikic/php-parser does, i.e. collect all comments above a node. Otherwise things like `/** @var */` declarations can't be handled, which could be problematic for some applications.
