### ISSUE TITLE
Inclusion of "utils.php" format_flags into the AST module (?)

### ISSUE THREAD

**Issue by ghost** [nikic/php-ast#62]
Hi,

I wrote a script using a modified version of "utils.php" including in this repository, but on upgrade to PHP 7.1, the script stopped working due to some modifications. I've got a temporary fix, but I think it would make more sense to hardwire this functionality into the extension itself.

I can understand that certain uses might benefit from not having the flags formatted, but it could be an option to ast_parse (default true or false) to list the flags as an array of strings or numbers. Managing the exclusive/combinable options manually is a bit much for non-performance critical logic.

**Comment by tomac120** [comment]
I find from a debugging perspective that it is easier to work with the flags as string array, and its not a significant performace drain (depends what you are doing of course). I want to be able to look at what flags an AST object has, to determine if I have missed something.

It would seem that "utils.php" formatting is an intergrated part of anyone's use of php-ast and therefore its changing parts at least should be integrated in some way (either as an array constant or an array get flags option, which I think would be most useful).

**Comment by nikic** [comment]
I've added an `ast\get_metadata()` function, which provides information about flags (and potentially other information in the future). This should be sufficient to implement whichever format you prefer on top of it.

The result format may not be final, I'm considering to make it return objects instead of associative arrays.

**Comment by elijah-z142** [comment]
Well, as it is, I don't think that there is a use-case for the raw data in this array except for generating an array of the flags on a given node.

I would suggest to move it further inwards to the API and expose a Node->getFlagsArray($asText=false) function. Then in format_flags of utils.php, just implode the array. Or something similar.

**Comment by tomac120** [comment]
Well, as it is, I don't think that there is a use-case for the raw data in this array except for generating an array of the flags on a given node.

I would suggest to move it further inwards to the API and expose a Node->getFlagsArray($asText=false) function. Then in format_flags of utils.php, just implode the array. Or something similar.

**Comment by nikic** [comment]
I'm providing the metadata functionality because this is the part that is volatile and tightly coupled to the version of the extension. It provides the necessary information to implement the AST dumper as well as your desired functionality on top of it, without having to keep track of the data yourself. I'm generally not willing to implement anything in C that can be trivially implemented in PHP (aka, not performance critical and does not require FFI).

I'd much rather move forward on #29 (which should now be easier, as the strong coupling between utils.php and the extension version no longer exists) and provide the functionality in PHP (as `get_flags($node)` rather than `$node->getFlags()` in that case.)

**Comment by tomac120** [comment]
Well, makes sense.

**Comment by tomac120** [comment]
Btw, the use case was to make a PHP -> Java converter ([http://www.runtimeconverter.com/](http://www.runtimeconverter.com/)) Its actually compiles and runs and doesn't just convert the syntax. It still needs a lot of work ie. features, like namespaces, but it is really working as a MVP / proof of concept.

Don't know how you feel about a PHP -> Java converter, but thats how I used it. The converter itself was written in Java, but uses a JSON export of the AST tree.

**Comment by nikic** [comment]
Closing this issue as get_metdata() has been exposed making util.php compatible across versions, and I don't want to add the printing implementation to the extension itself.
