### ISSUE TITLE
update util.php for version 50

### ISSUE THREAD

**Issue by TysonAndre** [nikic/php-ast#69]
util.php still needs to be updated to dump the name and doc comment of nodes generated with version 50.

- To do that, it needs to know which node kinds are decls
  It would also be useful for code which used to use Decl to have a utility to assert something is equivalent to a Decl (e.g. in the remote chance new decls get added in the future)
  (Actually, now that I think about it, there aren't dynamic property fields, so something with the field 'name' is always guaranteed to be part of a decl?)

Additionally, document that anything where kind_is_decl($node->kind) is true is guaranteed to have certain properties

**Comment by nikic** [comment]
Unless I'm missing something, this should already work, because name and docComment are not ordinary child nodes.

**Comment by nikic** [comment]
See for example https://github.com/nikic/php-ast/blob/master/tests/decl_normalization.phpt#L113, which already includes name and docComment in the output.

The point of the change was that you should *not* need to treat decls in any way specially. The only special thing about a decl is that it might have an endLineno, but otherwise it's just a normal node, with normal child nodes.
